// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZILXZX7Vl48z6dMxOrCg7uzKnonFo8dk',
    appId: '1:38064628768:web:2cc868b5e61b39af940845',
    messagingSenderId: '38064628768',
    projectId: 'cricketscoringpro',
    authDomain: 'cricketscoringpro.firebaseapp.com',
    storageBucket: 'cricketscoringpro.appspot.com',
    measurementId: 'G-R5XT6J1609',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7f2BtD_KQHkHUxTkcvbIxdtjXoAk9biw',
    appId: '1:38064628768:android:e12e05b104273e3b940845',
    messagingSenderId: '38064628768',
    projectId: 'cricketscoringpro',
    storageBucket: 'cricketscoringpro.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjxHZw_bfHy4sZo4xQFNW98zevrtg90fc',
    appId: '1:38064628768:ios:242dc71d4aff89ad940845',
    messagingSenderId: '38064628768',
    projectId: 'cricketscoringpro',
    storageBucket: 'cricketscoringpro.appspot.com',
    iosClientId: '38064628768-odkm6ok3otbqi4ehufjgh9amn0439fh5.apps.googleusercontent.com',
    iosBundleId: 'com.waheed.cricketScoring',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjxHZw_bfHy4sZo4xQFNW98zevrtg90fc',
    appId: '1:38064628768:ios:242dc71d4aff89ad940845',
    messagingSenderId: '38064628768',
    projectId: 'cricketscoringpro',
    storageBucket: 'cricketscoringpro.appspot.com',
    iosClientId: '38064628768-odkm6ok3otbqi4ehufjgh9amn0439fh5.apps.googleusercontent.com',
    iosBundleId: 'com.waheed.cricketScoring',
  );
}
